site_name: Firmament Autopilot
repo_url: https://github.com/FirmamentPilot/doc_src
nav:
- 概述: index.md
- 快速上手: getting_started.md
- 设备和驱动: device.md
- 组件: module.md
- 基于模型设计: mbd.md
- 模型接口定义: interface.md
- 仿真: simulation.md
- 贡献: contribute.md
    
theme: 
    name: readthedocs

